import 'package:flutter/material.dart';

import '../../design/zend_tokens.dart';

/// Pure visual splash screen. Navigation is handled by the session-restore
/// wrapper in app.dart.
///
/// Background follows the app's light/dark theme (ZendTheme.bgPrimary)
/// rather than the brand deep-green — the logo itself is dark green, so a
/// same-hued green backdrop would make it nearly disappear. This also
/// matches the native (pre-Flutter-engine) splash screen generated by
/// flutter_native_splash, so there's no visible flash/swap when this Dart
/// widget takes over from the native one.
class SplashScreen extends StatelessWidget {
  const SplashScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final zt = ZendTheme.of(context);
    return Scaffold(
      backgroundColor: zt.bgPrimary,
      body: const SafeArea(
        child: Center(
          child: Image(
            image: AssetImage('assets/logo/Zend.png'),
            width: 96,
            height: 96,
          ),
        ),
      ),
    );
  }
}
